### ISSUE TITLE
Crash in as_node_ensure_login_shm when remote servers are restarted

### ISSUE THREAD

**Issue by bsergean** [aerospike/aerospike-client-c#116]
We started seeing such a crash, after we upgraded from 5.0 to 5.2.6 (which fixed other problems with retries, so it was a good upgrade).

```
__restore_rt in section .text
as_node_ensure_login_shm + 36 in section .text
as_shm_tender + 1650 in section .text
start_thread + 219 in section .text
```

Does that ring a bell / is that sufficient info to troubleshoot ?

With this api: `as_node_ensure_login_shm(as_error* err, as_node* node)`, could some null ptr be passed in ?

ps: We are using a server at version `5.5.0.3-1`.

**Comment by BrianNichols** [comment]
"node->session" can definitely be null, but it's checked for null in as_node_ensure_login_shm().  It would be really helpful if you could identify which variable is null.

**Comment by BrianNichols** [comment]
Questions:
1) Is user authentication enabled on the server side for all nodes in the cluster?
2) Does the crash happen immediately on startup, after session expiration, when a node is added/removed or some other time?
3) Does the crash happen if shared memory is not enabled?
4) It's possible that the node itself is null.  Can you add an assert that node is not null in as_node_ensure_login_shm()?

**Comment by bsergean** [comment]
We are trying to use a new crash handler (breakpad) that should give us more info about the variables, not sure when this will be done though.

>>    Is user authentication enabled on the server side for all nodes in the cluster?
I'm pretty sure this is true.

>>    Does the crash happen immediately on startup, after session expiration, when a node is added/removed or some other time?
It happens when we do a rolling restart of the servers nodes.


>>    Does the crash happen if shared memory is not enabled?
Unclear, I will ask. It might be a bit hard to test.

>>    It's possible that the node itself is null. Can you add an assert that node is not null in as_node_ensure_login_shm()?
We try to not change the client code too much ourself. Could the client code be changed a bit (we could use a sha/branch build of an unreleased version) to confirm this ?

**Comment by BrianNichols** [comment]
I will get started on a branch that contains extra debugging code around as_node_ensure_login_shm().

**Comment by BrianNichols** [comment]
I have created a new C client branch "CLIENT-1650" that adds additional log statements around as_node_ensure_login_shm().  Try this branch with your application and make sure the application subscribes to the client log (ie. calls as_log_set_callback() once at startup).

**Comment by bsergean** [comment]
Thanks !
We are not using as_log_set_callback yet so I’ll have to check on how to do that. Are the log verbose ?
We have lots of logs in our app and are discarding quite a few / maybe we can setup a simpler environment to diagnose this problem.

**Comment by BrianNichols** [comment]
See: https://docs.aerospike.com/docs/client/c/usage/logging.html

A log statement will be generated every tend interval (usually 1 tend per second).

What simpler environment did you have in mind?

**Comment by bsergean** [comment]
We were able to reproduce the problem in a dev env with fewer machines.

As you probably guessed we had the client configured to use shared_memory, I was not aware of this setting. We’ll try to turn it off and see if it remove the crash, which sounds likely.

**Comment by bsergean** [comment]
Update: we've disabled use_shm in a test environment and the crash went away, so the crash is definitively linked to this mode.

**Comment by BrianNichols** [comment]
We have reproduced and fixed the crash when in shared memory.  A new C client will be released tomorrow.

Shared memory adds an extra layer of complexity, so we only recommend using it when there are a large number of client processes running on the same physical machine.

**Comment by bsergean** [comment]
That’s great news.

We have environments with large number of clients which is why we’ve used that feature. There’s actually one with an even higher number of clients that does not use it yet, and we’re looking forward to the fix to try it on.

**Comment by BrianNichols** [comment]
C client 5.2.7 is released: https://download.aerospike.com/download/client/c/notes.html#5.2.7

**Comment by bsergean** [comment]
That’s great, thanks for the quick fix. We’ll try to test it asap.

**Comment by bsergean** [comment]
Hello, so unfortunately the latest version does not seem to fix it (or we rebuilt incorrectly, I doubt it but I'll try a clean build).
I figure out how to enable logging (thanks to the doc page). I wrote a small program that uses a libuv timer to periodically issue a command after connection (retrieving all roles, which fails, but I don't think it matter).

It is quite easy for me now to reproduce the problem.

```
[2022-01-14 19:48:23.281] [stderr] [info] [AerospikeSharedDatabaseProvider.cpp:887] [src/main/aerospike/as_shm_cluster.c:1042][as_shm_create] 2 - Follow shared memory cluster: 9544
[2022-01-14 19:48:23.285] [stderr] [info] [AerospikeSharedDatabaseProvider.cpp:887] [src/main/aerospike/as_cluster.c:184][as_cluster_add_nodes_copy] 2 - Add node BB9E4601E0A0002 ip1:port
[2022-01-14 19:48:23.285] [stderr] [info] [AerospikeSharedDatabaseProvider.cpp:887] [src/main/aerospike/as_cluster.c:184][as_cluster_add_nodes_copy] 2 - Add node BB9E5601E0A0002 ip2:port
[2022-01-14 19:48:23.285] [stderr] [info] [AerospikeSharedDatabaseProvider.cpp:887] [src/main/aerospike/as_cluster.c:184][as_cluster_add_nodes_copy] 2 - Add node BB962601E0A0002 ip3:port
[2022-01-14 19:48:23.285] [stderr] [info] [AerospikeSharedDatabaseProvider.cpp:887] [src/main/aerospike/as_cluster.c:919][as_cluster_add_seed] 3 - Add seed ip1.port
[2022-01-14 19:48:23.285] [stderr] [info] [AerospikeSharedDatabaseProvider.cpp:887] [src/main/aerospike/as_cluster.c:919][as_cluster_add_seed] 3 - Add seed ip2.port
[2022-01-14 19:48:23.285] [stderr] [info] [AerospikeSharedDatabaseProvider.cpp:887] [src/main/aerospike/as_cluster.c:919][as_cluster_add_seed] 3 - Add seed ip3.port
[New Thread 0x7ffff67da700 (LWP 9548)]
[2022-01-14 19:48:23.286] [stderr] [info] [AerospikeSharedDatabaseProvider.cpp:198] Aerospike cluster successfully initialized. pid 9544
[2022-01-14 19:48:23.962] [stderr] [error] [AerospikeSharedDatabaseProvider.cpp:865] Could not retrieve roles from aerospike: error(81) AEROSPIKE_ROLE_VIOLATION at [src/main/aerospike/as_admin.c:326]
[2022-01-14 19:48:24.965] [stderr] [error] [AerospikeSharedDatabaseProvider.cpp:865] Could not retrieve roles from aerospike: error(81) AEROSPIKE_ROLE_VIOLATION at [src/main/aerospike/as_admin.c:326]
[2022-01-14 19:48:25.967] [stderr] [error] [AerospikeSharedDatabaseProvider.cpp:865] Could not retrieve roles from aerospike: error(81) AEROSPIKE_ROLE_VIOLATION at [src/main/aerospike/as_admin.c:326]
[2022-01-14 19:48:27.173] [stderr] [error] [AerospikeSharedDatabaseProvider.cpp:865] Could not retrieve roles from aerospike: error(81) AEROSPIKE_ROLE_VIOLATION at [src/main/aerospike/as_admin.c:326]
[2022-01-14 19:48:28.179] [stderr] [error] [AerospikeSharedDatabaseProvider.cpp:865] Could not retrieve roles from aerospike: error(81) AEROSPIKE_ROLE_VIOLATION at [src/main/aerospike/as_admin.c:326]
[2022-01-14 19:48:29.181] [stderr] [error] [AerospikeSharedDatabaseProvider.cpp:865] Could not retrieve roles from aerospike: error(81) AEROSPIKE_ROLE_VIOLATION at [src/main/aerospike/as_admin.c:326]
[2022-01-14 19:48:30.184] [stderr] [error] [AerospikeSharedDatabaseProvider.cpp:865] Could not retrieve roles from aerospike: error(81) AEROSPIKE_ROLE_VIOLATION at [src/main/aerospike/as_admin.c:326]
[2022-01-14 19:48:31.186] [stderr] [error] [AerospikeSharedDatabaseProvider.cpp:865] Could not retrieve roles from aerospike: error(81) AEROSPIKE_ROLE_VIOLATION at [src/main/aerospike/as_admin.c:326]
[2022-01-14 19:48:32.188] [stderr] [error] [AerospikeSharedDatabaseProvider.cpp:865] Could not retrieve roles from aerospike: error(81) AEROSPIKE_ROLE_VIOLATION at [src/main/aerospike/as_admin.c:326]
[2022-01-14 19:48:33.193] [stderr] [error] [AerospikeSharedDatabaseProvider.cpp:865] Could not retrieve roles from aerospike: error(81) AEROSPIKE_ROLE_VIOLATION at [src/main/aerospike/as_admin.c:326]
[2022-01-14 19:48:34.470] [stderr] [error] [AerospikeSharedDatabaseProvider.cpp:865] Could not retrieve roles from aerospike: error(-10) Socket read error: 104, ip3:port, 41196 at [src/main/aerospike/as_socket.c:248]
[2022-01-14 19:48:34.470] [stderr] [info] [AerospikeSharedDatabaseProvider.cpp:887] [src/main/aerospike/as_shm_cluster.c:251][as_shm_ensure_login_node] 0 - Failed to retrieve session token in shared memory prole tender: -10 Socket write error: ip3.port
[2022-01-14 19:48:35.471] [stderr] [info] [AerospikeSharedDatabaseProvider.cpp:887] [src/main/aerospike/as_shm_cluster.c:251][as_shm_ensure_login_node] 0 - Failed to retrieve session token in shared memory prole tender: -10 Socket write error: ip3.port
[2022-01-14 19:48:36.259] [stderr] [error] [AerospikeSharedDatabaseProvider.cpp:865] Could not retrieve roles from aerospike: error(81) AEROSPIKE_ROLE_VIOLATION at [src/main/aerospike/as_admin.c:326]
[2022-01-14 19:48:36.472] [stderr] [info] [AerospikeSharedDatabaseProvider.cpp:887] [src/main/aerospike/as_shm_cluster.c:251][as_shm_ensure_login_node] 0 - Failed to retrieve session token in shared memory prole tender: -10 Socket write error: ip3.port
[2022-01-14 19:48:37.473] [stderr] [info] [AerospikeSharedDatabaseProvider.cpp:887] [src/main/aerospike/as_shm_cluster.c:251][as_shm_ensure_login_node] 0 - Failed to retrieve session token in shared memory prole tender: -10 Socket write error: ip3.port
[2022-01-14 19:48:38.019] [stderr] [error] [AerospikeSharedDatabaseProvider.cpp:865] Could not retrieve roles from aerospike: error(81) AEROSPIKE_ROLE_VIOLATION at [src/main/aerospike/as_admin.c:326]
[2022-01-14 19:48:38.473] [stderr] [info] [AerospikeSharedDatabaseProvider.cpp:887] [src/main/aerospike/as_shm_cluster.c:251][as_shm_ensure_login_node] 0 - Failed to retrieve session token in shared memory prole tender: -10 Socket write error: ip3.port
[2022-01-14 19:48:39.021] [stderr] [error] [AerospikeSharedDatabaseProvider.cpp:865] Could not retrieve roles from aerospike: error(-10) Socket write error: 111, 10.30.96.229:3000, 41220 at [src/main/aerospike/as_socket.c:248]
[2022-01-14 19:48:39.474] [stderr] [info] [AerospikeSharedDatabaseProvider.cpp:887] [src/main/aerospike/as_shm_cluster.c:251][as_shm_ensure_login_node] 0 - Failed to retrieve session token in shared memory prole tender: -10 Socket write error: ip3.port
[2022-01-14 19:48:40.023] [stderr] [error] [AerospikeSharedDatabaseProvider.cpp:865] Could not retrieve roles from aerospike: error(81) AEROSPIKE_ROLE_VIOLATION at [src/main/aerospike/as_admin.c:326]
[2022-01-14 19:48:40.475] [stderr] [info] [AerospikeSharedDatabaseProvider.cpp:887] [src/main/aerospike/as_shm_cluster.c:251][as_shm_ensure_login_node] 0 - Failed to retrieve session token in shared memory prole tender: -10 Socket write error: ip3.port
[2022-01-14 19:48:41.475] [stderr] [info] [AerospikeSharedDatabaseProvider.cpp:887] [src/main/aerospike/as_shm_cluster.c:251][as_shm_ensure_login_node] 0 - Failed to retrieve session token in shared memory prole tender: -10 Socket write error: ip3.port
[2022-01-14 19:48:41.663] [stderr] [error] [AerospikeSharedDatabaseProvider.cpp:865] Could not retrieve roles from aerospike: error(81) AEROSPIKE_ROLE_VIOLATION at [src/main/aerospike/as_admin.c:326]
[2022-01-14 19:48:42.476] [stderr] [info] [AerospikeSharedDatabaseProvider.cpp:887] [src/main/aerospike/as_shm_cluster.c:251][as_shm_ensure_login_node] 0 - Failed to retrieve session token in shared memory prole tender: -10 Socket write error: ip3.port
[2022-01-14 19:48:42.476] [stderr] [info] [AerospikeSharedDatabaseProvider.cpp:887] [src/main/aerospike/as_cluster.c:501][as_cluster_remove_nodes_copy] 2 - Remove node BB962601E0A0002 10.30.96.98:3000
[2022-01-14 19:48:43.477] [stderr] [info] [AerospikeSharedDatabaseProvider.cpp:887] [src/main/aerospike/as_shm_cluster.c:251][as_shm_ensure_login_node] 0 - Failed to retrieve session token in shared memory prole tender: -10 Socket write error: ip3.port
[2022-01-14 19:48:43.562] [stderr] [error] [AerospikeSharedDatabaseProvider.cpp:865] Could not retrieve roles from aerospike: error(81) AEROSPIKE_ROLE_VIOLATION at [src/main/aerospike/as_admin.c:326]
[2022-01-14 19:48:44.477] [stderr] [info] [AerospikeSharedDatabaseProvider.cpp:887] [src/main/aerospike/as_cluster.c:501][as_cluster_remove_nodes_copy] 2 - Remove node BB9E5601E0A0002 ip3.port
[*** LOG ERROR #0001 ***] [2022-01-14 19:48:45] [stderr] {string pointer is null}
[2022-01-14 19:48:47.280] [stderr] [error] [AerospikeSharedDatabaseProvider.cpp:865] Could not retrieve roles from aerospike: error(81) AEROSPIKE_ROLE_VIOLATION at [src/main/aerospike/as_admin.c:326]
[2022-01-14 19:48:48.543] [stderr] [error] [AerospikeSharedDatabaseProvider.cpp:865] Could not retrieve roles from aerospike: error(81) AEROSPIKE_ROLE_VIOLATION at [src/main/aerospike/as_admin.c:326]
[2022-01-14 19:48:49.545] [stderr] [error] [AerospikeSharedDatabaseProvider.cpp:865] Could not retrieve roles from aerospike: error(81) AEROSPIKE_ROLE_VIOLATION at [src/main/aerospike/as_admin.c:326]

Thread 2 "al_aerospike_to" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7ffff67da700 (LWP 9548)]
0x00005555559789b9 in ck_pr_md_load_8 (target=0xd8 <error: Cannot access memory at address 0xd8>) at modules/common/target/Linux-x86_64/include/aerospike/ck/gcc/x86_64/ck_pr.h:198
198	modules/common/target/Linux-x86_64/include/aerospike/ck/gcc/x86_64/ck_pr.h: No such file or directory.
(gdb) bt
#0  0x00005555559789b9 in ck_pr_md_load_8 (target=0xd8 <error: Cannot access memory at address 0xd8>) at modules/common/target/Linux-x86_64/include/aerospike/ck/gcc/x86_64/ck_pr.h:198
#1  0x000055555597e49e in as_node_ensure_login_shm (err=0x7ffff67d9ad0, node=0x0) at src/main/aerospike/as_node.c:697
#2  0x000055555599fcd4 in as_shm_ensure_login_node (err=0x7ffff67d9ad0, node=0x0) at src/main/aerospike/as_shm_cluster.c:248
#3  0x000055555599fe1b in as_shm_ensure_login (cluster=0x555555ed3780, err=0x7ffff67d9ad0) at src/main/aerospike/as_shm_cluster.c:273
#4  0x00005555559a12f9 in as_shm_tender (userdata=0x555555ed3780) at src/main/aerospike/as_shm_cluster.c:801
#5  0x00007ffff7bc16ba in start_thread (arg=0x7ffff67da700) at pthread_create.c:333
#6  0x00007ffff68e251d in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:109
(gdb) 
```

It looks like a null check is required on node, not sure why it is null.

```
 694 as_status
 695 as_node_ensure_login_shm(as_error* err, as_node* node)
 696 {
 697     if (as_load_uint8(&node->perform_login) ||
 698         (node->session && node->session->expiration > 0 && cf_getns() >= node->session->expiration)) {
 699         as_socket sock;
```

**Comment by BrianNichols** [comment]
The line numbers in the stack-trace match up exactly with the source code in C client 5.2.6 (which has the bug) and does not match up with the source code in C client 5.2.7 (which fixed the bug).  Try compiling from scratch on C client 5.2.7.

**Comment by bsergean** [comment]
Ok thanks / I'll check and report. I was also surprised that 5.2.7 didn't fix it.
